name: Shell Commands

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World:"
      - name: multi-line script
        run: | #multi-line
          node -v
          npm -v
